ALTER VIEW CLIENTE AS
SELECT
A1_COD AS CODIGO, A1_LOJA AS LOJA, LTRIM(RTRIM(A1_NOME)) AS NOME, LTRIM(RTRIM(A1_NREDUZ)) AS NOME_FANTASIA, LTRIM(RTRIM(A1_CGC)) AS CGC,
 LTRIM(RTRIM(A1_DDD+A1_TEL)) AS TELEFONE, LTRIM(RTRIM(A1_EMAIL)) AS EMAIL,R_E_C_N_O_ AS REC
FROM     dbo.SA1010 (NOLOCK)
WHERE  (D_E_L_E_T_ = ' ')
