ALTER VIEW META_VENDEDOR AS
SELECT ZA9_FILIAL AS EMPRESA, ZA9_CODIGO AS CODIGO,CAST(ZA9_DATAI AS DATE) AS DATA_INICIAL,CAST(ZA9_DATAF AS DATE) AS DATA_FINAL,ZAA_VEND AS CODIGO_VENDEDOR,ZA9_DIAS AS DIAS,
ZA9_METAE AS META_ESPECIFICA,ZAA_METAQE AS META_QTD_PECAS,ZAA_METPRE AS META_PROSPECTO,
CASE ZAA_TIPVEN
WHEN 'P' THEN 'Pleno'
WHEN 'I' THEN 'Intermediario'
WHEN 'T' THEN 'Trenner'
WHEN 'V' THEN 'Varejo'
WHEN 'E' THEN 'Externo'
WHEN 'G' THEN 'Gerente'
WHEN 'C' THEN 'CallCenter'
WHEN 'J' THEN 'Junior'
WHEN 'S' THEN 'Senior'
WHEN 'M' THEN 'Master'
END
AS TIPO_VENDEDOR
,ZAA.R_E_C_N_O_ AS REC FROM ZA9010 (NOLOCK) ZA9 INNER JOIN ZAA010 (NOLOCK) ZAA ON ZAA_FILIAL = ZA9_FILIAL AND ZAA_CODIGO =ZA9_CODIGO
WHERE ZAA.D_E_L_E_T_ = '' AND ZA9.D_E_L_E_T_ = ''
