ALTER VIEW META_VENDEDOR AS
SELECT ZA9_FILIAL AS EMPRESA, ZA9_CODIGO AS CODIGO,CAST(ZA9_DATAI AS DATE) AS DATA_INICIAL,CAST(ZA9_DATAF AS DATE) AS DATA_FINAL,ZAA_VEND AS CODIGO_VENDEDOR,ZA9_DIAS AS DIAS,
ZAA_METAE AS META_ESPECIFICA,ZAA_METAQE AS META_QTD_PECAS,ZAA_METPRE AS META_PROSPECTO,
CASE ZAA_TIPVEN
WHEN 'P' THEN 'Pleno'
WHEN 'I' THEN 'Intermediario'
WHEN 'T' THEN 'Trenner'
WHEN 'V' THEN 'Varejo'
WHEN 'E' THEN 'Externo'
WHEN 'G' THEN 'Gerente'
WHEN 'C' THEN 'CallCenter'
WHEN 'J' THEN 'Junior'
WHEN 'S' THEN 'Senior'
WHEN 'M' THEN 'Master'
ELSE 'Padrao'
END
AS TIPO_VENDEDOR,CAST (ZA9_DTATU AS DATE) DATA_ATUALIZACAO, ZA9_HORAAT AS HORA_ATUALIZACAO,ZAB_QTDREA AS QUANTIDADE_REATIVOS,ZAB_QTDPRO AS QUANTIDADE_PROSPECTOS,
ZAB_QTDVEN AS QUANTIDADE_VENDAS, ZAB_VALTIC AS TICKET_MEDIO, ZAB_VALVEN AS VALOR_VENDIDO,ZAB_QTDDEV AS QUANTIDADE_DEVOLVIDO, ZAB_VALDEV AS VALOR_DEVOLVIDO
,ZAA.R_E_C_N_O_ AS REC FROM ZA9010 (NOLOCK) ZA9
INNER JOIN ZAA010 (NOLOCK) ZAA ON ZAA_FILIAL = ZA9_FILIAL AND ZAA_CODIGO =ZA9_CODIGO
INNER JOIN ZAB010 (NOLOCK) ZAB ON ZAA_FILIAL = ZAB_FILIAL AND ZAA_CODIGO =ZAB_CODIGO AND ZAA_VEND =ZAB_VEND
WHERE ZAA.D_E_L_E_T_ = '' AND ZA9.D_E_L_E_T_ = '' AND ZAB.D_E_L_E_T_ = ''