ALTER VIEW TOTALIZADOR_CARTEIRA AS
SELECT CODIGO_VENDEDOR,CODIGO,COUNT(*) AS TOTAL, SUM(CASE  WHEN  SITUACAO = 'Ativo' THEN 1 ELSE 0 END) AS ATIVOS,
SUM(CASE  WHEN  SITUACAO IN ('30 dias sem compras p1','60 dias sem compras p2') THEN 1 ELSE 0 END) AS PREINATIVOS,
SUM(CASE  WHEN  SITUACAO IN ('Bloqueado media de vendas','Inativo','Cessado') THEN 1 ELSE 0 END) AS INATIVOS
FROM CARTEIRA_CLIENTE
GROUP BY CODIGO,CODIGO_VENDEDOR