ALTER VIEW USUARIOS_SUPERVENDEDOR AS
SELECT LTRIM(RTRIM(A3_COD)) AS CODIGO, LTRIM(RTRIM(A3_SENHA)) AS SENHA, LTRIM(RTRIM(A3_NOME)) AS NOME, LTRIM(RTRIM(A3_NREDUZ)) AS NOME_REDUZIDO,R_E_C_N_O_ AS REC
FROM SA3010 (NOLOCK) WHERE D_E_L_E_T_ = '' AND A3_MSBLQL <> '1'