ALTER VIEW USUARIOS_COMISSAO AS
SELECT LTRIM(RTRIM(LOWER(ZA8_USUARI))) AS USUARIO, LTRIM(RTRIM(ZA8_SENHA)) AS SENHA, LTRIM(RTRIM(ZA8_VEND)) AS CODIGO_VENDEDOR,LTRIM(RTRIM(ZA8_GRUPO)) AS GRUPO,LTRIM(RTRIM(ZA8_FILS)) AS FILIAIS,R_E_C_N_O_ AS REC
FROM ZA8010 WHERE D_E_L_E_T_ = '' AND ZA8_MSBLQL <> '1'
